<?php $total = $block->_getCartTotal();
$threshold = $block->_getThreshold();
$markThres = floatval($total) > floatval($threshold) ? "&BigOnly" : "&LittleThings";
$markFlag = floatval($total) > floatval($threshold);
?>

<?php $country = $block->_getCountry(); ?>
<?php if ($country == 'AU') : ?>
    <script src="https://widgets.shophumm.com.au/content/scripts/price-info.js?productPrice=<?php echo $total ?>"></script>
<?php endif; ?>

<?php if ($country == 'NZ'):
    $ec_pattern = sprintf("%s%s%s", '<script src= "https://widgets.shophumm.co.nz/content/scripts/price-info.js?productPrice=', $total, '"></script>');
    echo $ec_pattern;
endif; ?>