<?php list($productPrice, $littleBig) = $block->_getProductPrice(); ?>
<?php $country = $block->_getCountry(); ?>
<?php if ($country == 'AU') : ?>
    <?php if (!$littleBig) : ?>
        <script src="https://widgets.shophumm.com.au/content/scripts/price-info.js?productPrice=<?php echo $productPrice ?>&LittleThings"></script>
    <?php else: ?>
        <script src="https://widgets.shophumm.com.au/content/scripts/price-info.js?productPrice=<?php echo $productPrice ?>&BigOnly"></script>
    <?php endif; ?>
<?php endif; ?>

<?php if ($country == 'NZ'): ?>
   <?php if (floatval($productPrice) < 1000) {
        $ec_pattern = sprintf("%s%s%s%s", '<script src= "https://widgets.shophumm.co.nz/content/scripts/price-info.js?productPrice=', $productPrice, '&LittleThings&little=F5', '"></script>');
    } else {
        $ec_pattern = sprintf("%s%s%s%s", '<script src= "https://widgets.shophumm.co.nz/content/scripts/price-info.js?productPrice=', $productPrice, 'BigThings', '"></script>');
    }
    echo $ec_pattern;
endif; ?>





