<?php list($productPrice, $littleBig) = $block->_getProductPrice(); ?>
<?php $country = $block->_getCountry(); ?>
<?php if ($country == 'AU') : ?>
    <script src="https://widgets.shophumm.com.au/content/scripts/price-info.js?productPrice=<?php echo $productPrice ?>"></script>
<?php endif; ?>

<?php if ($country == 'NZ'):
    $ec_pattern = sprintf("%s%s%s", '<script src= "https://widgets.shophumm.co.nz/content/scripts/price-info.js?productPrice=', $productPrice, '"></script>');
    echo $ec_pattern;
endif; ?>




