<div id="humm_simplepath">
        <div id="simplepath_unsupported">
            <a href="https://docs.shophumm.co.nz/ecommerce/magento_2/" target="_blank">
                <?= $block->escapeHtml(__('Humm NZ Magento 2 Documentation')); ?>
            </a>
        </div>
</div>

<div id="humm_simplepath_back">
    <p>If you don't have a humm merchant account you may join <a href="https://www.shophumm.co.nz/" target="_blank">here</a>.</p>
</div>
