<div id="humm_simplepath">
        <div id="simplepath_unsported">
            <?= $block->escapeHtml(__('Please review our configuration guide for configration.')); ?>
            <span class="note">
                <a href="https://docs.shophumm.com.au/ecommerce/magento_2/" target="_blank">
                (<?= $block->escapeHtml(__('More Information')); ?>)
                </a>
            </span>
        </div>
</div>

<div id="humm_simplepath_back">
    <a href="https://www.shophumm.com.au/" target="_blank">&laquo; <?= $block->escapeHtml(__('Back to register or connect an Humm payment account')); ?></a>
</div>
